"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const jsx_runtime_1 = require("react/jsx-runtime");
const formatTime_1 = require("../utils/formatTime");
const TotalStats = ({ dailyStats, appUsage }) => {
    const filteredApps = appUsage?.filter((app) => app.total_usage_seconds > 0) || [];
    return ((0, jsx_runtime_1.jsxs)("section", { className: "total-stats", children: [(0, jsx_runtime_1.jsx)("h2", { children: "\uC804\uCCB4 \uD1B5\uACC4" }), (0, jsx_runtime_1.jsxs)("div", { className: "stats-grid", children: [(0, jsx_runtime_1.jsxs)("div", { className: "stat-card", children: [(0, jsx_runtime_1.jsx)("h3", { children: "\uC0AC\uC6A9\uD55C \uC571 \uC218" }), (0, jsx_runtime_1.jsxs)("div", { className: "stat-value", children: [dailyStats?.total_apps || 0, "\uAC1C"] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "stat-card", children: [(0, jsx_runtime_1.jsx)("h3", { children: "\uCD1D \uC0AC\uC6A9 \uC2DC\uAC04" }), (0, jsx_runtime_1.jsx)("div", { className: "stat-value", children: (0, formatTime_1.formatTime)(dailyStats?.total_usage_seconds || 0) })] })] }), filteredApps.length > 0 ? ((0, jsx_runtime_1.jsxs)("div", { className: "app-usage-section", children: [(0, jsx_runtime_1.jsx)("h3", { children: "\uC571\uBCC4 \uC0AC\uC6A9\uB7C9" }), (0, jsx_runtime_1.jsx)("div", { className: "usage-list", children: filteredApps.map((app, index) => ((0, jsx_runtime_1.jsxs)("div", { className: "usage-item", children: [(0, jsx_runtime_1.jsx)("div", { className: "app-name", children: app.app_name }), (0, jsx_runtime_1.jsx)("div", { className: "usage-time", children: (0, formatTime_1.formatTime)(app.total_usage_seconds) })] }, index))) })] })) : ((0, jsx_runtime_1.jsx)("div", { className: "no-data", children: (0, jsx_runtime_1.jsx)("p", { children: "\uC544\uC9C1 \uC0AC\uC6A9\uB7C9 \uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uC7A0\uC2DC \uD6C4 \uB2E4\uC2DC \uD655\uC778\uD574\uC8FC\uC138\uC694." }) }))] }));
};
exports.default = TotalStats;
